variables:
  DOCKER_HOST: tcp://192.168.178.88:2375


stages:
  - Push to local Registry
  - Push dev2 to local Registry



docker pushlocal:
  image: docker:stable
  stage: Push to local Registry
  only:
    - master
  script:
    - echo "$LOCAL_REGISTRY" | docker login -u root --password-stdin service.joerg-tuttas.de:5555
    - docker build -t service.joerg-tuttas.de:5555/root/schuelerausweis .
    - docker push service.joerg-tuttas.de:5555/root/schuelerausweis
  tags:
    - myrunner

docker pushdev2local:
  image: docker:stable
  stage: Push dev2 to local Registry
  only:
    - dev2
  script:
    - echo "$LOCAL_REGISTRY" | docker login -u root --password-stdin service.joerg-tuttas.de:5555
    - docker build -t service.joerg-tuttas.de:5555/root/schuelerausweis:dev .
    - docker push service.joerg-tuttas.de:5555/root/schuelerausweis:dev
  tags:
    - myrunner