### Login
POST http://localhost:8080/login.html HTTP/1.1
content-type: application/x-www-form-urlencoded

user=tuttas&pwd=geheim

### Login Diklabu
POST https://diklabu.mm-bbs.de:8080/Diklabu/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "benutzer":"fiae18l.Brosowski",
    "kennwort":"recono39"

}

### Decode an id
POST https://localhost:8080/decode HTTP/1.1
content-type: application/json
key: geheim

{
    "id":"DmmGlsK7jUBw4n874BjtI4btyfBdtA8XBLRF3VGo2uUplkTCyPM0TTJjMzZDNH3xdGaYQKZRMJg6YjPn6+Q0/3enRwKUFZzfVbJiWbPjO4URaYmgG3MszJH3CKhmXh0tgJL0f0AQoV6TfVN72ihIoB5iFDKY09ycHbLalIH1T6VDA1hEUq4ONa6Tr2yzAo8s0aXd/Q2HES/ss2Ye2e483baqGa8MiJiOML2/dPRegACypb2UB3fZ6yZTMUJvVnlo1FF+y3dlTxaN8+c8w6tUD+u6aC6FImkEHBKUQCpFnQDgf2HxCBSOLg7ENim5Yh+J0t5k7un9NA4s0fvevG5nDQ=="
}

### Validate id
GET https://localhost:8080/validate?id=HVGbuC0WP8Dar62cI15Q9lt7467OtqyVhfm%2BJSsduMEv7hV/aZGx7tKGOleGbFVTx1yTtQ9e1NjaRRaQ2Y04I2pZXDSGUzubw1e3VcU5ADFIOuWY/giBldJZi5F3Ru8wntY%2Bm5sXNBSYQjn77YX95KWQ46IKo8ASYv%2BfMLXFZm9a/negue1JzGx4IBwiToemneIQluG8I8Ayyy04boQAbt2A96tOciiKRKggzjvgRLqG%2BjkvlqQry05OL5caR8LV9yIfTNiVh%2BMUnZ0xZxXBIHdgfh3GZ58BKlWb4KyvF47W31HxSjOqWkf1vE0tJehbbt1egAqCVqJb06C%2BtTTnLA== HTTP/1.1
content-type: text/html

### Validate id
POST https://130.61.61.100:8082/validate HTTP/1.1
content-type: application/json

{
    "id":"DmmGlsK7jUBw4n874BjtI4btyfBdtA8XBLRF3VGo2uUplkTCyPM0TTJjMzZDNH3xdGaYQKZRMJg6YjPn6+Q0/3enRwKUFZzfVbJiWbPjO4URaYmgG3MszJH3CKhmXh0tgJL0f0AQoV6TfVN72ihIoB5iFDKY09ycHbLalIH1T6VDA1hEUq4ONa6Tr2yzAo8s0aXd/Q2HES/ss2Ye2e483baqGa8MiJiOML2/dPRegACypb2UB3fZ6yZTMUJvVnlo1FF+y3dlTxaN8+c8w6tUD+u6aC6FImkEHBKUQCpFnQDgf2HxCBSOLg7ENim5Yh+J0t5k7un9NA4s0fvevG5nDQ=="
}

### dibalu abfrage
GET https://diklabu.mm-bbs.de:8080/Diklabu/api/v1/schueler/1234 HTTP/1.1
content-type: application/json
auth_token: geheim

### POwer Automate Test
POST https://prod-211.westeurope.logic.azure.com:443/workflows/e9aa6443ccf2416fb6ff1f54fe0b4fa8/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=gupicyKVuzEUjlOpO7l-BRLcKZdHubhmkEbY3p386f4 HTTP/1.1
Content-Type: application/json

{
  "nn": "Mustermann",
  "vn": "Max",
  "kl": "FIAE20J",
  "em": "Mustermann@mm-bbs.de",
  "v": "2021-08-01",
  "gd": "1997-04-11",
  "did": 1234,
  "valid": true
}

### POwer Automate 2 Test
POST https://prod-163.westeurope.logic.azure.com:443/workflows/ed5a7b85fb484e5fb07461fcb1ebd660/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=YOrcqZyS41k3ebhM6SaTOgGS9T0Z3ULCrVqVsK0-8U0 HTTP/1.1
Content-Type: application/json

{
  "nn": "Mustermann",
  "vn": "Max",
  "kl": "FIAE20J",
  "em": "Mustermann@mm-bbs.de",
  "v": "2021-08-01",
  "gd": "1997-04-11",
  "did": 1234,
  "valid": true
}

### Upload Image
POST https://localhost:8080/image HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundary
key: "DmmGlsK7jUBw4n874BjtI4btyfBdtA8XBLRF3VGo2uUplkTCyPM0TTJjMzZDNH3xdGaYQKZRMJg6YjPn6+Q0/3enRwKUFZzfVbJiWbPjO4URaYmgG3MszJH3CKhmXh0tgJL0f0AQoV6TfVN72ihIoB5iFDKY09ycHbLalIH1T6VDA1hEUq4ONa6Tr2yzAo8s0aXd/Q2HES/ss2Ye2e483baqGa8MiJiOML2/dPRegACypb2UB3fZ6yZTMUJvVnlo1FF+y3dlTxaN8+c8w6tUD+u6aC6FImkEHBKUQCpFnQDgf2HxCBSOLg7ENim5Yh+J0t5k7un9NA4s0fvevG5nDQ=="

--MyBoundary
Content-Disposition: form-data; name="image"; filename="qrcode.png"
Content-Type: image/png

< ./qrcode.png
--MyBoundary--


### Download Image
GET https://localhost:8080/image HTTP/1.1
key: "DmmGlsK7jUBw4n874BjtI4btyfBdtA8XBLRF3VGo2uUplkTCyPM0TTJjMzZDNH3xdGaYQKZRMJg6YjPn6+Q0/3enRwKUFZzfVbJiWbPjO4URaYmgG3MszJH3CKhmXh0tgJL0f0AQoV6TfVN72ihIoB5iFDKY09ycHbLalIH1T6VDA1hEUq4ONa6Tr2yzAo8s0aXd/Q2HES/ss2Ye2e483baqGa8MiJiOML2/dPRegACypb2UB3fZ6yZTMUJvVnlo1FF+y3dlTxaN8+c8w6tUD+u6aC6FImkEHBKUQCpFnQDgf2HxCBSOLg7ENim5Yh+J0t5k7un9NA4s0fvevG5nDQ=="

