### Login
POST http://localhost:8080/login.html HTTP/1.1
content-type: application/x-www-form-urlencoded

user=tuttas&pwd=geheim

### Login Diklabu
POST https://diklabu.mm-bbs.de:8080/Diklabu/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "benutzer":"fiae18l.Brosowski",
    "kennwort":"recono39"

}

### Decode an id
POST https://localhost:8080/decode HTTP/1.1
content-type: application/json
key: geheim

{
    "id":"LNZgOa11rFrnKM45zieJVjgYVim84XZ8OqKqjaRs7Xo2M73Zm4alHkPnBUCw4pQc1ituzKO1lOE2g3/83O4jDfbTb4M+WIsfmU1WW1MJzMoST/eKub1NPo51st+TYkCt1SBGpJSwTmgULS7M1sfbPCSWbiuSMBYKlAtXKd1llxeRjG7Macn7mQE8AXCZcc9t6taEjeewrnvc0xjs7AUyGUoRUnWf2LLJjHQi3JBl1jPIddTwSjhbnozVqKBV+uLK8n4wcBW5tR3O2n4bIgNr9lIbGdJSkllEuRL2AhRU7TmfiKFR7boBad7fNtQJTCtVIcAAiVInDjnxMmGPGfs8qA=="
}

### Validate id
GET https://localhost:8080/validate?id=WAR0VqblXDWuRWPmKkpXFMF%2B5Td79aqS/zurmp9Cnz2P7B8Zx7SZmPkb338P4Mv9Kp5v4Dt/caQJ2541uD9e%2B5YCuIlgtA98422AROL/kqBwJcgIqYRPIxhrArVRtiZfJ1G26gPld5wGPGiItAldNvohSO/PInOIkso1bUpzC5FdSnBgSaF9FFY03foqK0/I1iXMZvEBxAg9w50GACcj6MHc2ZExMu32AFiA3qXLop2cvisIATi/b732HtqSxHRsERHBKFfbSziuAyF%2BiMzNRlzhBu0o5NG%2B7IWkklzo3ddsERfliae9O7bH%2B1JxuIx3Eteg8RbkzKMkq48ReP6MbA== HTTP/1.1
content-type: text/html