### Login
POST http://localhost:8080/login.html HTTP/1.1
content-type: application/x-www-form-urlencoded

user=tuttas&pwd=geheim

### Login Diklabu
POST https://diklabu.mm-bbs.de:8080/Diklabu/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "benutzer":"fiae18l.Brosowski",
    "kennwort":"recono39"

}

### Decode an id
POST https://localhost:8080/decode HTTP/1.1
content-type: application/json
key: geheim

{
    "id":"I8WOESUgI3XLBaJ12uti2xfMCoYTztq2lnSVrGHUkatoXxngJBRDrGbTrz8vKLDHFaxoNIWrt4WAxYahFfPDPxMz3SKuNdf0Jk/6LRoIwBcKxIpvkPbJru6n0jcLctE15tKGfpspxjAeLT0IFZzHUzA5+tSgumCZRPFD4xwlOGR3ANU+hl7BWrm+qDc0qIbCsY9CdwQzhOA2wwYioijdoLgTBWOshgex7W/KCCPak/OdeDRJjeI20n+6PVUhPemn8K60cAzL/QKyKQvFAJmF3sFdoAhNH3Q+sKDpcbOVmVMGmacVi4E+fgqQEp9tH6y/6YEa3ZK05NdrD29WU3YCGQ=="
}

### Validate id
GET https://localhost:8080/validate?id=HVGbuC0WP8Dar62cI15Q9lt7467OtqyVhfm%2BJSsduMEv7hV/aZGx7tKGOleGbFVTx1yTtQ9e1NjaRRaQ2Y04I2pZXDSGUzubw1e3VcU5ADFIOuWY/giBldJZi5F3Ru8wntY%2Bm5sXNBSYQjn77YX95KWQ46IKo8ASYv%2BfMLXFZm9a/negue1JzGx4IBwiToemneIQluG8I8Ayyy04boQAbt2A96tOciiKRKggzjvgRLqG%2BjkvlqQry05OL5caR8LV9yIfTNiVh%2BMUnZ0xZxXBIHdgfh3GZ58BKlWb4KyvF47W31HxSjOqWkf1vE0tJehbbt1egAqCVqJb06C%2BtTTnLA== HTTP/1.1
content-type: text/html

### dibalu abfrage
GET https://diklabu.mm-bbs.de:8080/Diklabu/api/v1/schueler/1234 HTTP/1.1
content-type: application/json
auth_token: geheim