. $PSScriptRoot/ausweisprinter.ps1
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
$form1 = New-Object System.Windows.Forms.Form
$dateTimePicker1 = New-Object System.Windows.Forms.DateTimePicker
$label2 = New-Object System.Windows.Forms.Label
$buttonRemove = New-Object System.Windows.Forms.Button
$buttonAdd = New-Object System.Windows.Forms.Button
$listView2 = New-Object System.Windows.Forms.ListView
$statusBar1 = New-Object System.Windows.Forms.StatusBar
$listView1 = New-Object System.Windows.Forms.ListView
$textBox1 = New-Object System.Windows.Forms.TextBox
$label1 = New-Object System.Windows.Forms.Label
$button1 = New-Object System.Windows.Forms.Button


function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 19.04.2021 16:27
# Generated By: jtutt
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$global:form1 | Out-Null
$global:dateTimePicker1 | Out-Null
$global:label2 | Out-Null
$global:buttonRemove | Out-Null
$global:buttonAdd | Out-Null
$global:listView2 | Out-Null
$global:statusBar1 | Out-Null
$global:listView1 | Out-Null
$global:textBox1 | Out-Null
$global:label1 | Out-Null
$global:button1 | Out-Null

$Name = New-Object System.Windows.Forms.ColumnHeader
$Vorname = New-Object System.Windows.Forms.ColumnHeader
$gebDat = New-Object System.Windows.Forms.ColumnHeader
$sName = New-Object System.Windows.Forms.ColumnHeader
$sVorname = New-Object System.Windows.Forms.ColumnHeader
$sGebDat = New-Object System.Windows.Forms.ColumnHeader
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$handler_dateTimePicker1_ValueChanged= 
{
#TODO: Place custom script here
    if ($global:listView2.Items.Count -eq 0) {
        $global:button1.Enabled=$false
    }
    else {
       $global:button1.Enabled=$true
    }
    $global:statusBar1.Text=" "+$global:listView2.Items.Count+"/"+$global:allStudents.Count+" gewählt!"

}

$handler_buttonRemove_Click= 
{
    foreach ($e in $global:listView2.SelectedItems) {
        $global:allStudents.Add($e.Tag)
        Write-Host "Add $($e.Tag)"
        $global:listView2.Items.Remove($e)
        $global:listView1.Items.Add($e)
    }
    $global:button1.Text="Drucken ("+$global:listView2.Items.Count+")"
    if ($global:dateTimePicker1.Value.DayOfYear -ne $(Get-Date).DayOfYear) {
        $global:statusBar1.Text=" "+$global:listView2.Items.Count+"/"+$global:allStudents.Count+" gewählt!"
    }
    else {
        $global:statusBar1.Text=" "+$global:listView2.Items.Count+"/"+$global:allStudents.Count+" gewählt, Gültigkeitsdatum auswählen!"
    }
    if ($global:listView2.Items.Count -eq 0) {
        $global:button1.Enabled=$false
    }
}

$handler_buttonAdd_Click= 
{
    foreach ($e in $global:listView1.SelectedItems) {
        $global:allStudents.Remove($e.Tag)
        Write-Host "Remove $($e.tag)"
        $global:listView1.Items.Remove($e)
        $global:listView2.Items.Add($e)
    }
    $global:button1.Text="Drucken ("+$global:listView2.Items.Count+")"
    if ($global:dateTimePicker1.Value.DayOfYear -ne $(Get-Date).DayOfYear) {
        $global:button1.Enabled=$true
        $global:statusBar1.Text=" "+$global:listView2.Items.Count+"/"+$global:allStudents.Count+" gewählt!"
    }
    else {
       $global:statusBar1.Text=" "+$global:listView2.Items.Count+"/"+$global:allStudents.Count+" gewählt! Gültigkeitsdauer auswählen!"
    }
    
}

$handler_textBox1_KeyPress= 
{
#TODO: Place custom script here

}

$handler_listView1_SelectedIndexChanged= 
{
#TODO: Place custom script here

}

$handler_textBox1_TextChanged= 
{
    filterListView
}

$handler_button1_Click= 
{
#TODO: Place custom script here
    $num=1;
    $max=$global:listView2.Items.Count
    foreach ($item in $global:listView2.Items) {
           $global:statusBar1.Text=" Bearbeite $num von $max"
           $details = Get-Pupil -id $item.Tag.did
           Write-Host $details
           $item.Tag.kl=$details.klassen | ForEach-Object {if ($_.ID_KATEGORIE -eq 0) {return $_.KNAME}}
           $item.Tag.v="$($global:dateTimePicker1.Value.Year)-$($global:dateTimePicker1.Value.Month)-$($global:dateTimePicker1.Value.Day)"
           Write-Host $item.Tag
           $num++
    }
    $global:statusBar1.Text=" Drucke....."
  
    $global:listView2.Items.TAG |  Print-IDCard -Verbose
      foreach ($item in $global:listView2.Items) {
        $global:allStudents.Add($item.Tag)
        $global:listView2.Items.Remove($item)
        $global:listView1.Items.Add($item)
    }
    $global:button1.Text="Drucken (0)"
    $global:button1.Enabled=$false
    $global:statusBar1.Text=" "+$global:listView2.Items.Count+"/"+$global:allStudents.Count+" gewählt!"
}


$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 416
$System_Drawing_Size.Width = 894
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.MaximizeBox = $False
$form1.Name = "form1"
$form1.Text = "Ausweisdrucker"

$dateTimePicker1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 671
$System_Drawing_Point.Y = 299
$dateTimePicker1.Location = $System_Drawing_Point
$dateTimePicker1.Name = "dateTimePicker1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 200
$dateTimePicker1.Size = $System_Drawing_Size
$dateTimePicker1.TabIndex = 11
$dateTimePicker1.add_ValueChanged($handler_dateTimePicker1_ValueChanged)

$form1.Controls.Add($dateTimePicker1)

$label2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 671
$System_Drawing_Point.Y = 273
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 188
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 10
$label2.Text = "Gültigkeit"

$form1.Controls.Add($label2)
 

$buttonRemove.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 313
$System_Drawing_Point.Y = 217
$buttonRemove.Location = $System_Drawing_Point
$buttonRemove.Name = "buttonRemove"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$buttonRemove.Size = $System_Drawing_Size
$buttonRemove.TabIndex = 8
$buttonRemove.Text = "<--"
$buttonRemove.UseVisualStyleBackColor = $True
$buttonRemove.add_Click($handler_buttonRemove_Click)

$form1.Controls.Add($buttonRemove)


$buttonAdd.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 313
$System_Drawing_Point.Y = 175
$buttonAdd.Location = $System_Drawing_Point
$buttonAdd.Name = "buttonAdd"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$buttonAdd.Size = $System_Drawing_Size
$buttonAdd.TabIndex = 7
$buttonAdd.Text = "-->"
$buttonAdd.UseVisualStyleBackColor = $True
$buttonAdd.add_Click($handler_buttonAdd_Click)

$form1.Controls.Add($buttonAdd)


$listView2.Columns.Add($sName)|Out-Null
$listView2.Columns.Add($sVorname)|Out-Null
$listView2.Columns.Add($sGebDat)|Out-Null
$listView2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 413
$System_Drawing_Point.Y = 32
$listView2.Location = $System_Drawing_Point
$listView2.Name = "listView2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 352
$System_Drawing_Size.Width = 252
$listView2.Size = $System_Drawing_Size
$listView2.Sorting = 1
$listView2.TabIndex = 6
$listView2.UseCompatibleStateImageBehavior = $False
$listView2.View = 1

$form1.Controls.Add($listView2)

$statusBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 0
$System_Drawing_Point.Y = 394
$statusBar1.Location = $System_Drawing_Point
$statusBar1.Name = "statusBar1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 894
$statusBar1.Size = $System_Drawing_Size
$statusBar1.TabIndex = 5
$statusBar1.Text = "statusBar1"

$form1.Controls.Add($statusBar1)


$listView1.Columns.Add($Name)|Out-Null
$listView1.Columns.Add($Vorname)|Out-Null
$listView1.Columns.Add($gebDat)|Out-Null
$listView1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 32
$listView1.Location = $System_Drawing_Point
$listView1.Name = "listView1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 352
$System_Drawing_Size.Width = 269
$listView1.Size = $System_Drawing_Size
$listView1.Sorting = 1
$listView1.TabIndex = 4
$listView1.UseCompatibleStateImageBehavior = $False
$listView1.View = 1
$listView1.add_SelectedIndexChanged($handler_listView1_SelectedIndexChanged)

$form1.Controls.Add($listView1)

$textBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 57
$System_Drawing_Point.Y = 6
$textBox1.Location = $System_Drawing_Point
$textBox1.Name = "textBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 225
$textBox1.Size = $System_Drawing_Size
$textBox1.TabIndex = 3
$textBox1.add_TextChanged($handler_textBox1_TextChanged)
$textBox1.add_KeyPress($handler_textBox1_KeyPress)

$form1.Controls.Add($textBox1)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 9
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 38
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 2
$label1.Text = "Filter:"

$form1.Controls.Add($label1)

$button1.BackColor = [System.Drawing.Color]::FromArgb(255,0,120,215)

$button1.DataBindings.DefaultDataSourceUpdateMode = 0
$button1.Enabled = $False
$button1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,0)
$button1.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 671
$System_Drawing_Point.Y = 325
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 59
$System_Drawing_Size.Width = 200
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 0
$button1.Text = "Drucken (0)"
$button1.UseVisualStyleBackColor = $False
$button1.add_Click($handler_button1_Click)

$form1.Controls.Add($button1)

$Name.Name = "Name"
$Name.Text = "Name"
$Name.Width = 100

$Vorname.Name = "Vorname"
$Vorname.Text = "Vorname"
$Vorname.Width = 89

$gebDat.Name = "gebDat"
$gebDat.Text = "GebDat"
$gebDat.Width = 75

$sName.Name = "sName"
$sName.Text = "Name"
$sName.Width = 88

$sVorname.Name = "sVorname"
$sVorname.Text = "Vorname"
$sVorname.Width = 84

$sGebDat.Name = "sGebDat"
$sGebDat.Text = "GebDat"
$sGebDat.Width = 75

#endregion Generated Form Code

#Save the initial state of the form
#$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
#$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
#$form1.ShowDialog()| Out-Null

} #End Function

function filterListView() {
    $data = $global:allStudents | where-Object {$_.toString() -like "*$($global:textBox1.Text)*"} 
    #Write-Host $data  
    
    $global:listView1.Items.Clear()
    foreach ($student in $data) {  
        [System.Windows.Forms.ListViewItem]$item = New-Object System.Windows.Forms.ListViewItem
        $item.Tag=$student
        $item.Text=$student.nn
        $item.SubItems.Add($student.vn)
        $item.SubItems.Add($student.gd)
        $global:listView1.Items.Add($item)
    } 
}

#Call the Function
GenerateForm
Import-Module diklabu
Get-Keystore "$HOME/keystore.json"
if (-not (Test-Path "$HOME/keystore.json")) {
    Write-Host "Keine Diklabu AnmeldeDaten vorhanden" -BackgroundColor DarkRed
    $cred = Get-Credential
    Login-Diklabu -uri "https://diklabu.mm-bbs.de:8080/Diklabu/api/v1/" -credential $cred
}
else {    
    Login-Diklabu 
    Write-Host "Angemeldet am diklabu" -BackgroundColor DarkGreen
}
Write-Host "Lese alle Schülerdaten...." -BackgroundColor DarkGreen
$pupils=get-pupils 
$allStudents=New-Object System.Collections.ArrayList     
[System.Windows.Forms.ListViewItem]$item = New-Object System.Windows.Forms.ListViewItem 
foreach ($p in $pupils) {
    
    $global:item = New-Object System.Windows.Forms.ListViewItem 

    $s = New-Object StudentId
    $s.bpid=$p.ID_MMBBS
    $s.did=$p.id
    $s.gd=$p.GEBDAT
    $s.kl=
    $s.nn=$p.NNAME
    $s.vn=$p.VNAME
    $s.v="2021-08-01"
    [void]$allStudents.Add($s)
    
    $item.Tag=$s
    $item.Text=$s.nn
    [void]$item.SubItems.Add($s.vn)
    [void]$item.SubItems.Add($s.gd)
    
    #$Name.Text=$s.nn
    #$Vorname.Text=$s.vn
    #$gebDat.Text=$s.gd
    
    
    [void]$listView1.Items.Add($item)
    
}
#
$statusBar1.Text=""+$allStudents.Count+" Schüler eingelesen, bitte Schüler auswählen!"
#Show the Form
$form1.ShowDialog()| Out-Null 
